### ISSUE TITLE
Way to support IPV6?

### ISSUE THREAD

**Issue by mayeaux** [RD17/DeTor#1]
Otherwise I can't check a lot of IPS, thanks

**Comment by sochix** [comment]
Hi @mayeaux ! Will add it to the next release

**Comment by mayeaux** [comment]
Awesome, ty!

**Comment by gjsmith66** [comment]
Any update on adding IPV6 support?  Would be a great enhancement

**Comment by sochix** [comment]
TorDNESL porotcol doesn't support ipv6 as for now
